name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ§° Maintenance"
    label: "chore"
autolabeler:
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
    body:
      - "/JIRA-[0-9]{1,4}/"
change-template: "- $TITLE @$AUTHOR (#$NUMBER) $BASE_REF_NAME -> $HEAD_REF_NAME $URL $BODY"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## What's Changed 

  $CHANGES
  $CONTRIBUTORS
  $PREVIOUS_TAG
  $REPOSITORY
  $OWNER
