name: "Build Cache"
description: "Build Cache"

outputs:
  cache-hit:
    description: "Whether the cache was hit or not"
    value: ${{ steps.build-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Build
      id: build-cache
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ hashFiles('**/yarn.lock', '**/package.json', '**/src/**') }}
