name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  cache-name: cache-node-modules

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2

        with:
          # caching node_modules
          path: node_modules
          # cache key
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # cache key for cross-branch cache.
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install Dependencies
        # if no cache hit, install deps.
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs:
      - install

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # reading node_modules
          path: node_modules
          # cache key
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # cache key for cross-branch cache
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - run: npm run build
