name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs:
      - install

    steps:
      - uses: actions/checkout@v2

      - run: npm run build
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
  # install:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #     - run: npm install
  #     # - uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: docker-artifact
  #     #     path: path/to/artifacts
  #     #     retention-days: 1

  # lint:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - install

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #     - run: npm run lint

  # # build:
  # #   runs-on: ubuntu-latest
  # #   needs:
  # #     - install

  # #   steps:
  # #     - run: npm run build

  # # test:
  # #   runs-on: ubuntu-latest
  # #   needs:
  # #     - build

  # #   steps:
  # #     - uses: actions/checkout@v2
  # #     - run: npm run test
