name: PR Workflow CI

on: pull_request

jobs:
  # create two jobs. The first job produces some output and the second job uses that output
  first_job:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.date.outputs.time }}
    steps:
      - name: Get the time
        id: date
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Get the time
        run: echo "The time was ${{ needs.first_job.outputs.time }}"
