name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
      - uses: actions/checkout@v2
      - name: Cache or Retrieve Node Modules
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm test

  lint:
    runs-on: ubuntu-latest
