name: PR Workflow CI

on: pull_request

jobs:
  Cancel-Previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  Install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules

      - name: Download dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

  Lint:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - run: yarn lint

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - run: yarn test

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - uses: ./.github/actions/build-restore
        id: cache-build

      - name: Create New Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: yarn build

  Upload-Artifact:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-restore
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: "build-artifact"
          path: build/

  GCP-Upload:
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-restore
      - uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/667117874450/locations/global/workloadIdentityPools/gh-pool/providers/github"
          service_account: "gh-oidc@ps-ref-arch.iam.gserviceaccount.com"
      - run: echo process.env
      - uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./build
          destination: "ps-ref-arch-web-client/"

      - run: ls -la /home/runner/work/mobx-ref-arch/mobx-ref-arch
      - run: echo "hello world"
      - run: cd /home/runner/work/mobx-ref-arch/mobx-ref-arch && cat gha-creds-*

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
