name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - run: npm install

  build:
    runs-on: ubuntu-latest
    needs:
      - install

    steps:
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs:
      - install

    steps:
      - uses: actions/checkout@v2
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - run: npm run test
