name: PR Workflow CI

on: pull_request

jobs:
  Cancel-Previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  Install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules

      - name: Download dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

  Lint:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - run: yarn lint

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - run: yarn test

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - uses: ./.github/actions/build-restore
        id: cache-build

      - name: Create New Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: yarn build

  Upload-Artifact:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-restore
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GITHUB_REPOSITORY }}-${{ env.GITHUB_REF }}-${{ env.GITHUB_SHA }}
          path: build

  GCP-Authenticate:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/667117874450/locations/global/workloadIdentityPools/gh-pool/providers/github"
          service_account: "gh-oidc@ps-ref-arch.iam.gserviceaccount.com"

      - name: "Use gcloud CLI"
        run: "gcloud info"

  GCP-Upload:
    needs: [Build, GCP-Authenticate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - uses: ./.github/actions/build-restore
        run: ls -la
      - uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./build
          destination: "ps-ref-arch-web-client/"
