name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  parse_commits:
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.parse.outputs.commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse commits
        id: parse
        run: |
          # Parse the commits and output the result
          echo "::set-output name=commits::$(git log --pretty=tformat:"%s|%aN|%aD|%h" --no-merges)"

  echo_commits:
    runs-on: ubuntu-latest
    needs: parse_commits
    steps:
      - name: Echo commits
        run: |
          # Use the output from the previous job
          echo "${{ join(needs.parse_commits.outputs.commits, '\n') }}"

  Release:
    needs: [parse_commits, echo_commits]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

        name: Send custom JSON data to Slack workflow
        id: slack
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Feature branch: ${{ github.event.pull_request.head.ref }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Target branch: ${{ github.event.pull_request.base.ref }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Commits: ${{ join(needs.parse_commits.outputs.commits, '\n') }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  #     - uses: anothrNick/github-tag-action@1.36.0
  #       id: tag
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         WITH_V: true

  #     - uses: release-drafter/release-drafter@v5
  #       id: draft
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         commitish: 'main'
  #         tag: ${{ steps.tag.outputs.tag }}
  #         prerelease: true

  #     - run: echo "${{ steps.draft.outputs.body }}"
  #     - run: echo "${{ steps.tag.outputs.tag }}"

  #     - uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ steps.tag.outputs.tag }}

  # Custom-Slack-Notification:
  #   needs: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: alexuxui/slacktion@v3.0
  #       with:
  #         url: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         token: ${{ secrets.TOKEN }}
  #         body: ${{ steps.draft.outputs.body }}

  # Notify-Slack:
  #   needs: Release
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Slack Notification
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_MESSAGE: ${{ steps.draft.outputs.body }}
  #         SLACK_ICON: https://assets.website-files.com/6166408856602addeee5f874/627d940d412b116983a4ad07_footer_logo.svg
  #         SLACK_FOOTER: 'test footer'
  #         SLACK_COLOR: ${{ job.status }}
  #         MSG_MINIMAL: commit
