name: Release Drafter

on:
  push:
    branches:
      - main
      - release
      - test

permissions:
  contents: write
  pull-requests: write

jobs:
  Generate_Git_Log_Output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Git Log Output
        id: git_log
        run: >-
          echo "::set-output name=git_log::$(git log --pretty=format:'%s' --no-merges --reverse)"

  Echo_Git_Log_Output:
    runs-on: ubuntu-latest
    needs: Generate_Git_Log_Output
    steps:
      - name: Echo Git Log Output
        run: |
          echo "${{ needs.Generate_Git_Log_Output.outputs.git_log }}"

  Generate_Diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Diff
        run: |
          echo git log ${{ github.event.after }}...${{ github.event.before }} --pretty=format:'%s' --reverse

  Compare_Before_And_After_Commits:
    needs: Generate_Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compare Before And After Commits
        id: compare
        run: |
          echo "::set-output name=diff::$(git log ${{ github.event.after }}...${{ github.event.before }})"

  Echo_Commits:
    runs-on: ubuntu-latest
    needs: Compare_Before_And_After_Commits
    steps:
      - name: Echo Commits
        run: |
          echo ${{ needs.Compare_Before_And_After_Commits.outputs.diff }}

  Dump_Action_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Action Environment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  Parse_Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse package version
        id: parse
        run: |
          echo "::set-output name=version::$(npm pkg get version)"

  Release:
    needs: [Parse_Version, Compare_Before_And_After_Commits]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

        name: Send custom JSON data to Slack workflow
        id: slack
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          # try it out here: https://app.slack.com/block-kit-builder/
          payload: |
            {
              "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployed Version: ${{ fromJSON(needs.Parse_Version.outputs.version) }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Diff: ${{ fromJSON(needs.Compare_Before_And_After_Commits.outputs.diff) }}"
                  }
                },      
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View the PR>"
                  }
                }

              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_HOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
