name: Release Drafter

on:
  push:
    branches:
      - main
      - release
      - test

permissions:
  contents: write
  pull-requests: write

jobs:
  Generate_Diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Diff
        run: |
          git log ${{ github.event.after }}...${{ github.event.before }} --pretty=format:"%s"

  Compare_Before_And_After_Commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compare Before And After Commits
        run: |
          echo "::set-output name=diff::$(git log ${{ github.event.after }}...${{ github.event.before }})"

  Echo_Commits:
    runs-on: ubuntu-latest
    needs: Compare_Before_And_After_Commits
    steps:
      - name: Echo Commits
        run: |
          echo ${{ needs.Compare_Before_And_After_Commits.outputs.diff }}

  Dump_Action_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Action Environment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  Get_Main_Head:
    runs-on: ubuntu-latest
    outputs:
      main_head: ${{ steps.get-main-head.outputs.main_head }}
    steps:
      - name: Get Main Head
        id: get-main-head
        run: |
          echo "::set-output name=main_head::$(git rev-parse HEAD)"

  Parse_Commits:
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.parse.outputs.commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse commits
        id: parse
        run: |
          echo "::set-output name=commits::$(git log --pretty=tformat:"%s" --no-merges)"

  Parse_Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse package version
        id: parse
        run: |
          echo "::set-output name=version::$(npm pkg get version)"

  Release:
    needs: [Parse_Commits, Parse_Version, Compare_Before_And_After_Commits]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

        name: generate diff
        id: diff
        run: |
          echo "::set-output name=diff::$(git log ${{ github.event.after }}...${{ github.event.before }} --pretty=format:'%s')"      

        name: Send custom JSON data to Slack workflow
        id: slack
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          # try it out here: https://app.slack.com/block-kit-builder/
          payload: |
            {
              "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployed Version: ${{ fromJSON(needs.Parse_Version.outputs.version) }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Diff: ${{ fromJSON(needs.Compare_Before_And_After_Commits.outputs.diff) }}"
                  }
                },      
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View the PR>"
                  }
                }

              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_HOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
