name: Release Drafter

on: pull_request

permissions:
  contents: write
  pull-requests: write # for release-drafter/release-drafter to add label to PR

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  echo_tag:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ steps.create_tag.outputs.tag }}"

  update_release_draft:
    needs: create_tag
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: "main"
          tag: ${{ steps.create_tag.outputs.tag }}

  create_release:
    runs-on: ubuntu-latest
    needs: [update_release_draft]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}

  post_release_notes:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ steps.draft.outputs.body }}"

  Notify-Slack:
    needs: post_release_notes
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: ${{ steps.draft.outputs.body }}
          SLACK_ICON: https://assets.website-files.com/6166408856602addeee5f874/627d940d412b116983a4ad07_footer_logo.svg
          SLACK_FOOTER: "(click the commit ID to see the diff)"
          MSG_MINIMAL: commit
          SLACK_COLOR: ${{ job.status }}
