name: Release Drafter

on:
  push:
    branches:
      - main

# on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  Release:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: anothrNick/github-tag-action@1.36.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: "main"
          tag: ${{ steps.tag.outputs.tag }}
          prerelease: true

      - uses: crazy-max/ghaction-dump-context@v1

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}

  Notify-Slack:
    needs: Release
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: ${{ steps.draft.outputs.body }}
          SLACK_ICON: https://assets.website-files.com/6166408856602addeee5f874/627d940d412b116983a4ad07_footer_logo.svg
          SLACK_FOOTER: "${{ steps.draft.outputs.html_url }} - ${{ steps.draft.outputs.tag_name }} "
          MSG_MINIMAL: commit
          SLACK_COLOR: ${{ job.status }}
