name: Release Drafter

on: pull_request

permissions:
  contents: write
  pull-requests: write # for release-drafter/release-drafter to add label to PR

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: "main"

  create_release:
    runs-on: ubuntu-latest
    needs: [update_release_draft]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}

  post_release_notes:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ steps.draft.outputs.body }}"

  Notify-Slack:
    needs: post_release_notes
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: ${{ steps.draft.outputs.body }}
          SLACK_ICON: https://assets.website-files.com/6166408856602addeee5f874/627d940d412b116983a4ad07_footer_logo.svg
          SLACK_FOOTER: "(click the commit ID to see the diff)"
          MSG_MINIMAL: commit
          SLACK_COLOR: ${{ job.status }}
