name: Test ENV CD Workflow
# yoo
on:
  push:
    branches:
      - test

jobs:
  # Install:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/deps-restore
  #       id: cache-node-modules

  #     - name: Download dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: yarn install --immutable

  # Download:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #     - name: Display structure of downloaded files
  #       run: ls -R

  GCP-Upload:
    # needs: Download
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      # - uses: ./.github/actions/deps-restore
      # - uses: ./.github/actions/build-restore
      # id: cache-build

      # - name: Create New Build
      #   if: steps.cache-build.outputs.cache-hit != 'true'
      #   run: yarn build

      - uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/667117874450/locations/global/workloadIdentityPools/gh-pool/providers/github"
          service_account: "gh-oidc@ps-ref-arch.iam.gserviceaccount.com"

      - uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./build-${{ github.event.before }}
          destination: "ps-ref-arch-web-client/"
# cool cool cool
