name: Test ENV CD Workflow

on:
  push:
    branches:
      - test

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

  Download-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R

